import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import {
  cancelProductionOrder, completeProductionOrder, completeProductionStage, createProductionOrder,
  getProductionOrder, getProductionStage, issueProductionMaterials, listProductionLosses,
  listProductionOrders, listProductionStages, recordProductionOutput, releaseBatchQuality,
  releaseProductionOrder, resolveProductionRework, startProductionStage,
  type ProductionLossWorkspace as LossData, type ProductionOrder, type ProductionOrderWorkspace as OrderData,
  type ProductionStage, type ProductionStageWorkspace as StageData,
} from '../api/manufacturingExecution';
import { StatusBadge } from './StatusBadge';
import {
  applyFailure, date, dateTime, Datum, decimal, Detail, DetailHead, emptyFeedback, Empty, Field,
  FormActions, LineTable, ManufacturingWorkspace, nullable, numeric, useManufacturingContextKey,
} from './ManufacturingWorkspaceShell';

export function ProductionOrderWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<OrderData | null>(null);
  const [selected, setSelected] = useState<ProductionOrder | null>(null); const [editing, setEditing] = useState(false);
  const [form, setForm] = useState(blankOrder()); const [search, setSearch] = useState(''); const [status, setStatus] = useState('');
  const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(emptyFeedback()); const key = useRef<string | null>(null);
  const [output, setOutput] = useState({ event_type: 'GOOD', quantity: '', reason_code: '', notes: '' });
  const refresh = useCallback(async () => { setLoading(true); try { setWorkspace(await listProductionOrders({ q: search || undefined, status: status || undefined, sort, page })); } catch (error) { applyFailure(setFeedback, error, 'Unable to load production orders.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page]);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { setSelected(null); setEditing(false); setSearch(''); setStatus(''); setPage(1); setFeedback(emptyFeedback()); }, [contextKey]);
  useEffect(() => { key.current = null; }, [form]);
  async function choose(id: string) { setFeedback(emptyFeedback()); try { setSelected(await getProductionOrder(id)); setEditing(false); } catch (error) { applyFailure(setFeedback, error, 'Unable to load production-order detail.'); } }
  function startNew() { setSelected(null); setForm(blankOrder()); setEditing(true); setFeedback(emptyFeedback()); }
  function chooseLine(id: string) { const line = workspace?.lookups.schedule_lines.find((item) => item.id === id); setForm((value) => ({ ...value, production_schedule_line_id: id, planned_start_date: line?.planned_start_date ?? '', planned_end_date: line?.planned_end_date ?? '' })); }
  async function save(event: FormEvent) {
    event.preventDefault(); const fields: Record<string, string> = {};
    if (!form.order_number.trim()) fields.order_number = 'Order number is required.';
    if (!form.batch_number.trim()) fields.batch_number = 'Batch number is required.';
    if (!form.production_schedule_line_id) fields.production_schedule_line_id = 'Choose a released schedule line.';
    if (Object.keys(fields).length) { setFeedback({ error: 'Correct the highlighted order fields.', success: null, fields }); return; }
    setBusy(true); try { key.current ??= crypto.randomUUID(); const result = await createProductionOrder({ order_number: form.order_number.trim().toUpperCase(), batch_number: form.batch_number.trim().toUpperCase(), production_schedule_line_id: form.production_schedule_line_id, planned_start_date: form.planned_start_date || null, planned_end_date: form.planned_end_date || null, notes: nullable(form.notes) }, key.current); key.current = null; await refresh(); setSelected(await getProductionOrder(result.id)); setEditing(false); setFeedback({ error: null, success: 'Draft production order created from the released schedule.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to create the production order.'); } finally { setBusy(false); }
  }
  async function command(action: 'RELEASE' | 'ISSUE_MATERIALS' | 'COMPLETE' | 'CANCEL' | 'QUALITY_RELEASE') {
    if (!selected) return; const reason = action === 'CANCEL' ? window.prompt('Cancellation reason') : null; if (action === 'CANCEL' && !reason?.trim()) return;
    setBusy(true); try {
      if (action === 'RELEASE') await releaseProductionOrder(selected, crypto.randomUUID());
      else if (action === 'ISSUE_MATERIALS') await issueProductionMaterials(selected, crypto.randomUUID());
      else if (action === 'COMPLETE') await completeProductionOrder(selected, crypto.randomUUID());
      else if (action === 'QUALITY_RELEASE') await releaseBatchQuality(selected, crypto.randomUUID());
      else await cancelProductionOrder(selected, reason!.trim(), crypto.randomUUID());
      await refresh(); setSelected(await getProductionOrder(selected.id));
      setFeedback({ error: null, success: ({ RELEASE: 'Production order released.', ISSUE_MATERIALS: 'Reserved material issued by FEFO.', COMPLETE: 'Production order completed.', CANCEL: 'Production order cancelled.', QUALITY_RELEASE: 'Batch quality released.' })[action], fields: {} });
    } catch (error) { applyFailure(setFeedback, error, 'Unable to complete the production command.'); } finally { setBusy(false); }
  }
  async function recordOutput(event: FormEvent) {
    event.preventDefault();
    if (!selected || numeric(output.quantity) <= 0) { setFeedback({ error: 'Enter a positive output quantity.', success: null, fields: { output_quantity: 'Quantity must be greater than zero.' } }); return; }
    if (output.event_type !== 'GOOD' && !output.reason_code.trim()) { setFeedback({ error: 'A reason code is required for loss or rework.', success: null, fields: { output_reason: 'Enter a concise reason code.' } }); return; }
    setBusy(true); try {
      await recordProductionOutput(selected, { event_type: output.event_type, quantity: output.quantity, reason_code: output.event_type === 'GOOD' ? null : output.reason_code.trim().toUpperCase(), notes: nullable(output.notes) }, crypto.randomUUID());
      await refresh(); setSelected(await getProductionOrder(selected.id)); setOutput({ event_type: 'GOOD', quantity: '', reason_code: '', notes: '' });
      setFeedback({ error: null, success: 'Production output recorded and batch totals recalculated.', fields: {} });
    } catch (error) { applyFailure(setFeedback, error, 'Unable to record production output.'); } finally { setBusy(false); }
  }
  return <ManufacturingWorkspace code="PRO-ORDER" title="Production Orders" description="Turn released schedule lines into controlled batches, issue reserved material, and complete accountable output." notice="Orders preserve the released recipe and route snapshots; every stock issue, transition, and quality gate is server-authoritative." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} onNew={workspace?.allowed_actions.includes('CREATE') ? startNew : undefined} headings={['Order / batch', 'Output', 'Plan', 'Progress', 'Quality', 'Status']} rows={workspace?.data.map((row) => [<><b>{row.order_number}</b><small>{row.batch_number} · v{row.record_version}</small></>, <><b>{row.output_sku.code}</b><small>{row.output_sku.name}</small></>, `${decimal(row.planned_quantity)} ${row.uom_code}`, `${row.completed_stage_count}/${row.stage_count} stages`, <StatusBadge status={row.quality_status} />, <StatusBadge status={row.status} />]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {editing ? <form className="requisition-form" onSubmit={save}><fieldset disabled={busy}><div className="requisition-field-grid"><label>Order number<input value={form.order_number} onChange={(e) => setForm({ ...form, order_number: e.target.value })} /><Field text={feedback.fields.order_number} /></label><label>Batch number<input value={form.batch_number} onChange={(e) => setForm({ ...form, batch_number: e.target.value })} /><Field text={feedback.fields.batch_number} /></label><label className="wide">Released schedule line<select aria-label="Released schedule line" value={form.production_schedule_line_id} onChange={(e) => chooseLine(e.target.value)}><option value="">Select scheduled output</option>{workspace?.lookups.schedule_lines.map((line) => <option key={line.id} value={line.id}>{line.schedule_number}/{line.line_number} · {line.output_sku.code} · {decimal(line.planned_quantity)} {line.uom_code}</option>)}</select><Field text={feedback.fields.production_schedule_line_id} /></label><label>Planned start<input type="date" value={form.planned_start_date} onChange={(e) => setForm({ ...form, planned_start_date: e.target.value })} /></label><label>Planned end<input type="date" value={form.planned_end_date} onChange={(e) => setForm({ ...form, planned_end_date: e.target.value })} /></label><label className="wide">Notes<textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><FormActions busy={busy} onClose={() => setEditing(false)} submit="Create production order" /></fieldset></form>
      : selected ? <Detail><DetailHead status={selected.status} version={selected.record_version} /><dl className="control-definition"><Datum text="Order / batch" value={`${selected.order_number} / ${selected.batch_number}`} /><Datum text="Schedule" value={selected.schedule.number} /><Datum text="Output" value={`${selected.output_sku.code} · ${decimal(selected.planned_quantity)} ${selected.uom_code}`} /><Datum text="Recipe / route" value={`${selected.recipe.code} r${selected.recipe.revision} / ${selected.route.code}`} /><Datum text="Dates" value={`${date(selected.planned_start_date)} – ${date(selected.planned_end_date)}`} /><Datum text="Quality" value={<StatusBadge status={selected.quality_status} />} /><Datum text="Accounted" value={`${decimal(selected.accounted_quantity)} / ${decimal(selected.planned_quantity)} ${selected.uom_code}`} /><Datum text="Good / loss / rework" value={`${decimal(selected.good_quantity)} / ${decimal(selected.loss_quantity)} / ${decimal(selected.rework_quantity)}`} /><Datum wide text="Notes" value={selected.notes ?? 'No notes'} /></dl>
        <h4>Material issue</h4><LineTable heads={['Material', 'Required', 'Issued', 'Lots']} rows={selected.materials?.map((line) => [<><b>{line.component_sku.code}</b><small>{line.component_sku.name}</small></>, `${decimal(line.required_quantity)} ${line.uom_code}`, `${decimal(line.issued_quantity)} ${line.uom_code}`, line.issues.length ? line.issues.map((issue) => `${issue.lot_code}: ${decimal(issue.quantity)}`).join(', ') : 'Not issued']) ?? []} />
        <h4>Route execution</h4><LineTable heads={['Seq', 'Operation', 'Work centre', 'Minutes', 'Status']} rows={selected.stages?.map((stage) => [String(stage.sequence_no), stage.operation_name, stage.work_center_code, stage.actual_minutes === null ? decimal(stage.planned_minutes) : `${decimal(stage.actual_minutes)} / ${decimal(stage.planned_minutes)}`, <StatusBadge status={stage.status} />]) ?? []} />
        {selected.allowed_actions.includes('RECORD_OUTPUT') ? <form className="requisition-form manufacturing-command" onSubmit={recordOutput}><fieldset disabled={busy}><h4>Record production output</h4><div className="requisition-field-grid"><label>Output type<select aria-label="Direct output type" value={output.event_type} onChange={(event) => setOutput({ ...output, event_type: event.target.value })}><option>GOOD</option><option>LOSS</option><option>REWORK</option></select></label><label>Quantity<input aria-label="Direct output quantity" type="number" min="0.000001" step="0.000001" value={output.quantity} onChange={(event) => setOutput({ ...output, quantity: event.target.value })} /><Field text={feedback.fields.output_quantity} /></label>{output.event_type !== 'GOOD' ? <label>Reason code<input aria-label="Direct output reason code" value={output.reason_code} onChange={(event) => setOutput({ ...output, reason_code: event.target.value })} /><Field text={feedback.fields.output_reason} /></label> : null}<label className="wide">Notes<textarea rows={2} value={output.notes} onChange={(event) => setOutput({ ...output, notes: event.target.value })} /></label></div><div className="form-actions"><button className="primary" type="submit">Record output</button></div></fieldset></form> : null}
        <div className="form-actions">{selected.allowed_actions.filter((action) => action !== 'RECORD_OUTPUT').map((action) => <button key={action} className={action === 'RELEASE' || action === 'ISSUE_MATERIALS' || action === 'COMPLETE' || action === 'QUALITY_RELEASE' ? 'primary' : 'secondary'} disabled={busy} onClick={() => void command(action as Parameters<typeof command>[0])}>{orderActionLabel(action)}</button>)}</div></Detail>
      : <Empty text="Choose a production order or create one from a released schedule line." />}
  </ManufacturingWorkspace>;
}

export function ProductionStageWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<StageData | null>(null); const [selected, setSelected] = useState<ProductionStage | null>(null);
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1);
  const [actualMinutes, setActualMinutes] = useState(''); const [notes, setNotes] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(emptyFeedback());
  const refresh = useCallback(async () => { setLoading(true); try { setWorkspace(await listProductionStages({ q: search || undefined, status: status || undefined, sort, page })); } catch (error) { applyFailure(setFeedback, error, 'Unable to load production stages.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { setSelected(null); setSearch(''); setStatus(''); setPage(1); setFeedback(emptyFeedback()); }, [contextKey]);
  async function choose(id: string) { setFeedback(emptyFeedback()); try { const row = await getProductionStage(id); setSelected(row); setActualMinutes(row.planned_minutes); setNotes(row.notes ?? ''); } catch (error) { applyFailure(setFeedback, error, 'Unable to load stage detail.'); } }
  async function command(action: 'START' | 'COMPLETE') {
    if (!selected) return; if (action === 'COMPLETE' && numeric(actualMinutes) < 0) { setFeedback({ error: 'Actual minutes cannot be negative.', success: null, fields: { actual_minutes: 'Enter zero or a positive duration.' } }); return; }
    setBusy(true); try { action === 'START' ? await startProductionStage(selected, crypto.randomUUID()) : await completeProductionStage(selected, { actual_minutes: actualMinutes, notes: nullable(notes) }, crypto.randomUUID()); await refresh(); const row = await getProductionStage(selected.id); setSelected(row); setActualMinutes(row.planned_minutes); setFeedback({ error: null, success: action === 'START' ? 'Stage started; an immutable start event was recorded.' : 'Stage completed with actual time.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to complete the stage command.'); } finally { setBusy(false); }
  }
  return <ManufacturingWorkspace code="PRO-STAGE" title="Stage Execution" description="Run route operations in sequence and capture actual work-centre time against the production batch." notice="A stage can start only after its predecessor completes; start and completion events are immutable." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} headings={['Order / batch', 'Seq', 'Operation', 'Work centre', 'Minutes', 'Status']} rows={workspace?.data.map((row) => [<><b>{row.production_order.number}</b><small>{row.production_order.batch_number}</small></>, String(row.sequence_no), row.operation_name, row.work_center_code, row.actual_minutes === null ? decimal(row.planned_minutes) : `${decimal(row.actual_minutes)} / ${decimal(row.planned_minutes)}`, <StatusBadge status={row.status} />]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {selected ? <Detail><DetailHead status={selected.status} version={selected.record_version} /><dl className="control-definition"><Datum text="Order" value={`${selected.production_order.number} / ${selected.production_order.batch_number}`} /><Datum text="Sequence" value={selected.sequence_no} /><Datum text="Operation" value={selected.operation_name} /><Datum text="Work centre" value={selected.work_center_code} /><Datum text="Planned minutes" value={decimal(selected.planned_minutes)} /><Datum text="Started" value={dateTime(selected.started_at)} /><Datum text="Completed" value={dateTime(selected.completed_at)} /><Datum wide text="Notes" value={selected.notes ?? 'No notes'} /></dl>{selected.allowed_actions.includes('COMPLETE') ? <div className="requisition-field-grid inventory-command"><label>Actual minutes<input aria-label="Actual minutes" type="number" min="0" step="0.001" value={actualMinutes} onChange={(e) => setActualMinutes(e.target.value)} /><Field text={feedback.fields.actual_minutes} /></label><label className="wide">Completion note<textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} /></label></div> : null}<div className="form-actions">{selected.allowed_actions.includes('START') ? <button className="primary" disabled={busy} onClick={() => void command('START')}>Start stage</button> : null}{selected.allowed_actions.includes('COMPLETE') ? <button className="primary" disabled={busy} onClick={() => void command('COMPLETE')}>Complete stage</button> : null}</div></Detail> : <Empty text="Choose a route stage to start or complete." />}
  </ManufacturingWorkspace>;
}

export function ProductionLossWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<LossData | null>(null); const [selected, setSelected] = useState<ProductionOrder | null>(null);
  const [form, setForm] = useState({ event_type: 'GOOD', quantity: '', reason_code: '', notes: '' }); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(emptyFeedback()); const key = useRef<string | null>(null);
  const refresh = useCallback(async (keepId?: string) => { setLoading(true); try { const data = await listProductionLosses({ q: search || undefined, status: status || undefined, sort, page }); setWorkspace(data); const id = keepId ?? selected?.id; if (id) setSelected(data.data.find((row) => row.id === id) ?? null); } catch (error) { applyFailure(setFeedback, error, 'Unable to load yield and loss records.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page, selected?.id]);
  useEffect(() => { void refresh(); }, [contextKey, search, status, sort, page]); useEffect(() => { setSelected(null); setSearch(''); setStatus(''); setPage(1); setFeedback(emptyFeedback()); }, [contextKey]); useEffect(() => { key.current = null; }, [form, selected?.record_version]);
  function choose(id: string) { setSelected(workspace?.data.find((row) => row.id === id) ?? null); setFeedback(emptyFeedback()); }
  async function record(event: FormEvent) {
    event.preventDefault(); if (!selected || numeric(form.quantity) <= 0) { setFeedback({ error: 'Enter a positive output quantity.', success: null, fields: { quantity: 'Quantity must be greater than zero.' } }); return; }
    if (form.event_type !== 'GOOD' && !form.reason_code.trim()) { setFeedback({ error: 'A reason code is required for loss or rework.', success: null, fields: { reason_code: 'Enter a concise reason code.' } }); return; }
    setBusy(true); try { key.current ??= crypto.randomUUID(); await recordProductionOutput(selected, { event_type: form.event_type, quantity: form.quantity, reason_code: form.event_type === 'GOOD' ? null : form.reason_code.trim().toUpperCase(), notes: nullable(form.notes) }, key.current); key.current = null; await refresh(selected.id); setForm({ event_type: 'GOOD', quantity: '', reason_code: '', notes: '' }); setFeedback({ error: null, success: 'Production output recorded and the batch totals recalculated.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to record production output.'); } finally { setBusy(false); }
  }
  async function resolve(id: string, disposition: string) { const notes = window.prompt(`${disposition === 'RECOVERED' ? 'Recovery' : 'Scrap'} resolution notes`); if (!notes?.trim()) return; setBusy(true); try { await resolveProductionRework(id, { disposition, notes: notes.trim() }, crypto.randomUUID()); await refresh(selected?.id); setFeedback({ error: null, success: `Rework ${disposition.toLowerCase()} and yield totals recalculated.`, fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to resolve rework.'); } finally { setBusy(false); } }
  return <ManufacturingWorkspace code="PRO-LOSS" title="Yield / Loss / Rework" description="Account every planned output unit as good product, process loss, or controlled rework." notice="Completion is blocked until planned quantity is fully accounted and every rework event is resolved." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} headings={['Order / batch', 'Planned', 'Good', 'Loss', 'Rework', 'Status']} rows={workspace?.data.map((row) => [<><b>{row.order_number}</b><small>{row.batch_number}</small></>, `${decimal(row.planned_quantity)} ${row.uom_code}`, decimal(row.good_quantity), decimal(row.loss_quantity), <>{decimal(row.rework_quantity)}<small>{row.open_rework_count} open</small></>, <StatusBadge status={row.status} />]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {selected ? <Detail><DetailHead status={selected.status} version={selected.record_version} /><div className="manufacturing-balance"><span>Planned<b>{decimal(selected.planned_quantity)}</b></span><span>Accounted<b>{decimal(selected.accounted_quantity)}</b></span><span>Good<b>{decimal(selected.good_quantity)}</b></span><span>Loss<b>{decimal(selected.loss_quantity)}</b></span></div>{selected.allowed_actions.includes('RECORD_OUTPUT') ? <form className="requisition-form manufacturing-command" onSubmit={record}><fieldset disabled={busy}><div className="requisition-field-grid"><label>Output type<select aria-label="Output type" value={form.event_type} onChange={(e) => setForm({ ...form, event_type: e.target.value })}>{workspace?.lookups.event_types.map((type) => <option key={type}>{type}</option>)}</select></label><label>Quantity<input aria-label="Output quantity" type="number" min="0.000001" step="0.000001" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} /><Field text={feedback.fields.quantity} /></label>{form.event_type !== 'GOOD' ? <label>Reason code<input aria-label="Reason code" value={form.reason_code} onChange={(e) => setForm({ ...form, reason_code: e.target.value })} /><Field text={feedback.fields.reason_code} /></label> : null}<label className="wide">Notes<textarea rows={2} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><div className="form-actions"><button className="primary" type="submit">Record output</button></div></fieldset></form> : null}<LineTable heads={['Seq', 'Type / reason', 'Quantity', 'Rework state', 'Recorded', 'Action']} rows={selected.outputs?.map((row) => [String(row.sequence_no), <><b>{row.event_type}</b><small>{row.reason_code ?? 'No reason code'}</small></>, `${decimal(row.quantity)} ${row.uom_code}`, <StatusBadge status={row.rework_status} />, dateTime(row.recorded_at), row.allowed_actions.includes('RESOLVE') ? <span className="table-actions"><button className="secondary compact-button" disabled={busy} onClick={() => void resolve(row.id, 'RECOVERED')}>Recover</button><button className="secondary compact-button" disabled={busy} onClick={() => void resolve(row.id, 'SCRAPPED')}>Scrap</button></span> : '—']) ?? []} /></Detail> : <Empty text="Choose an in-process or completed order to review yield." />}
  </ManufacturingWorkspace>;
}

function blankOrder() { return { order_number: '', batch_number: '', production_schedule_line_id: '', planned_start_date: '', planned_end_date: '', notes: '' }; }
function orderActionLabel(action: string) { return ({ RELEASE: 'Release order', ISSUE_MATERIALS: 'Issue reserved materials', COMPLETE: 'Complete order', CANCEL: 'Cancel order', QUALITY_RELEASE: 'Release quality' } as Record<string, string>)[action] ?? action; }
