import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import {
  completeLabSample, createFoodSafetyHold, createLabSample, getLabSample, getSafetyRecord,
  listLabSamples, listSafetyRecords, releaseBatchQuality, releaseFoodSafetyHold, resolveQualityDeviation,
  type LabSample, type LabWorkspace as LabData, type SafetyRecord, type SafetyWorkspace as SafetyData,
} from '../api/manufacturingExecution';
import { StatusBadge } from './StatusBadge';
import {
  applyFailure, dateTime, Datum, decimal, Detail, DetailHead, emptyFeedback, Empty, Field,
  FormActions, LineTable, ManufacturingWorkspace, nullable, useManufacturingContextKey,
} from './ManufacturingWorkspaceShell';

export function LabSampleWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<LabData | null>(null); const [selected, setSelected] = useState<LabSample | null>(null); const [editing, setEditing] = useState(false);
  const [form, setForm] = useState(blankSample()); const [values, setValues] = useState<Record<string, string>>({}); const [notes, setNotes] = useState<Record<string, string>>({});
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(emptyFeedback()); const key = useRef<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); try { setWorkspace(await listLabSamples({ q: search || undefined, status: status || undefined, sort, page })); } catch (error) { applyFailure(setFeedback, error, 'Unable to load lab samples.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { setSelected(null); setEditing(false); setSearch(''); setStatus(''); setPage(1); setFeedback(emptyFeedback()); }, [contextKey]); useEffect(() => { key.current = null; }, [form]);
  async function choose(id: string) { setFeedback(emptyFeedback()); try { const row = await getLabSample(id); setSelected(row); setEditing(false); setValues(Object.fromEntries((row.results ?? []).map((result) => [result.id, result.numeric_value ?? result.text_value ?? (result.boolean_value === null ? '' : result.boolean_value ? 'true' : 'false')]))); setNotes(Object.fromEntries((row.results ?? []).map((result) => [result.id, result.notes ?? '']))); } catch (error) { applyFailure(setFeedback, error, 'Unable to load sample detail.'); } }
  function startNew() { setSelected(null); setForm(blankSample()); setEditing(true); setFeedback(emptyFeedback()); }
  function chooseOrder(id: string) { const order = workspace?.lookups.production_orders.find((row) => row.id === id); const spec = workspace?.lookups.specifications.find((row) => !order || row.sku_id === order.output_sku?.id || row.catalog_item_id === order.output_sku?.id) ?? workspace?.lookups.specifications[0]; setForm((row) => ({ ...row, production_order_id: id, specification_id: spec?.id ?? '' })); }
  async function save(event: FormEvent) {
    event.preventDefault(); const fields: Record<string, string> = {}; if (!form.sample_number.trim()) fields.sample_number = 'Sample number is required.'; if (!form.production_order_id) fields.production_order_id = 'Choose a completed production order.'; if (!form.specification_id) fields.specification_id = 'Choose an active specification.'; if (Object.keys(fields).length) { setFeedback({ error: 'Correct the highlighted sample fields.', success: null, fields }); return; }
    setBusy(true); try { key.current ??= crypto.randomUUID(); const result = await createLabSample({ sample_number: form.sample_number.trim().toUpperCase(), production_order_id: form.production_order_id, specification_id: form.specification_id, sampled_at: new Date(form.sampled_at).toISOString(), notes: nullable(form.notes) }, key.current); key.current = null; await refresh(); await choose(result.id); setFeedback({ error: null, success: 'Lab sample created with an immutable specification snapshot.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to create the lab sample.'); } finally { setBusy(false); }
  }
  async function complete(event: FormEvent) {
    event.preventDefault(); if (!selected?.results) return; const fields: Record<string, string> = {}; selected.results.forEach((result) => { if (result.is_required && !values[result.id]?.trim()) fields[`results.${result.id}`] = 'A result value is required.'; }); if (Object.keys(fields).length) { setFeedback({ error: 'Enter every required result.', success: null, fields }); return; }
    const results = selected.results.map((result) => ({ result_id: result.id, ...(result.value_type === 'NUMERIC' ? { numeric_value: values[result.id] || null } : result.value_type === 'BOOLEAN' ? { boolean_value: values[result.id] === '' ? null : values[result.id] === 'true' } : { text_value: values[result.id] || null }), notes: nullable(notes[result.id] ?? '') }));
    setBusy(true); try { await completeLabSample(selected, { results }, crypto.randomUUID()); await refresh(); await choose(selected.id); setFeedback({ error: null, success: 'Sample completed and specification results evaluated.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to complete the lab sample.'); } finally { setBusy(false); }
  }
  return <ManufacturingWorkspace code="QC-LAB" title="Lab & Samples" description="Capture release samples against versioned specifications and evaluate each required parameter." notice="Failed parameters automatically raise a quality deviation and place the production batch on hold." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} onNew={workspace?.allowed_actions.includes('CREATE') ? startNew : undefined} headings={['Sample', 'Order / batch', 'Specification', 'Sampled', 'Status']} rows={workspace?.data.map((row) => [row.sample_number, <><b>{row.production_order.number}</b><small>{row.production_order.batch_number}</small></>, `${row.specification.code} r${row.specification.version}`, dateTime(row.sampled_at), <StatusBadge status={row.status} />]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {editing ? <form className="requisition-form" onSubmit={save}><fieldset disabled={busy}><div className="requisition-field-grid"><label>Sample number<input value={form.sample_number} onChange={(e) => setForm({ ...form, sample_number: e.target.value })} /><Field text={feedback.fields.sample_number} /></label><label>Sampled at<input type="datetime-local" value={form.sampled_at} onChange={(e) => setForm({ ...form, sampled_at: e.target.value })} /></label><label className="wide">Completed production order<select aria-label="Completed production order" value={form.production_order_id} onChange={(e) => chooseOrder(e.target.value)}><option value="">Select batch</option>{workspace?.lookups.production_orders.map((order) => <option key={order.id} value={order.id}>{order.number} / {order.batch_number} · {order.output_sku?.code}</option>)}</select><Field text={feedback.fields.production_order_id} /></label><label className="wide">Specification<select aria-label="Specification" value={form.specification_id} onChange={(e) => setForm({ ...form, specification_id: e.target.value })}><option value="">Select specification</option>{workspace?.lookups.specifications.map((spec) => <option key={spec.id} value={spec.id}>{spec.code} · {spec.name}</option>)}</select><Field text={feedback.fields.specification_id} /></label><label className="wide">Notes<textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><FormActions busy={busy} onClose={() => setEditing(false)} submit="Create lab sample" /></fieldset></form>
      : selected ? <Detail><DetailHead status={selected.status} version={selected.record_version} /><dl className="control-definition"><Datum text="Sample" value={selected.sample_number} /><Datum text="Production batch" value={`${selected.production_order.number} / ${selected.production_order.batch_number}`} /><Datum text="Specification" value={`${selected.specification.code} r${selected.specification.version}`} /><Datum text="Sampled" value={dateTime(selected.sampled_at)} /><Datum text="Completed" value={dateTime(selected.completed_at)} /><Datum wide text="Notes" value={selected.notes ?? 'No notes'} /></dl><form className="requisition-form" onSubmit={complete}><fieldset disabled={busy || !selected.allowed_actions.includes('COMPLETE')}><div className="lab-result-list">{selected.results?.map((result) => <div className="requisition-line-card" key={result.id}><div className="result-heading"><b>{result.sequence_no}. {result.code} · {result.name}</b><StatusBadge status={result.result} /></div><small>{requirement(result)}</small><div className="requisition-field-grid">{result.value_type === 'BOOLEAN' ? <label>Result<select aria-label={`${result.code} result`} value={values[result.id] ?? ''} onChange={(e) => setValues({ ...values, [result.id]: e.target.value })}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select><Field text={feedback.fields[`results.${result.id}`]} /></label> : <label>Result<input aria-label={`${result.code} result`} type={result.value_type === 'NUMERIC' ? 'number' : 'text'} step="any" value={values[result.id] ?? ''} onChange={(e) => setValues({ ...values, [result.id]: e.target.value })} /><Field text={feedback.fields[`results.${result.id}`]} /></label>}<label>Result notes<input aria-label={`${result.code} notes`} value={notes[result.id] ?? ''} onChange={(e) => setNotes({ ...notes, [result.id]: e.target.value })} /></label></div></div>)}</div>{selected.allowed_actions.includes('COMPLETE') ? <div className="form-actions"><button className="primary" type="submit">Complete and evaluate sample</button></div> : null}</fieldset></form></Detail>
      : <Empty text="Choose a lab sample or create one for a completed production batch." />}
  </ManufacturingWorkspace>;
}

export function QualitySafetyWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<SafetyData | null>(null); const [selected, setSelected] = useState<SafetyRecord | null>(null); const [editing, setEditing] = useState(false); const [form, setForm] = useState(blankHold()); const [releaseOrderId, setReleaseOrderId] = useState('');
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(emptyFeedback()); const key = useRef<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); try { setWorkspace(await listSafetyRecords({ q: search || undefined, status: status || undefined, sort, page })); } catch (error) { applyFailure(setFeedback, error, 'Unable to load food-safety records.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { setSelected(null); setEditing(false); setSearch(''); setStatus(''); setPage(1); setReleaseOrderId(''); setFeedback(emptyFeedback()); }, [contextKey]); useEffect(() => { key.current = null; }, [form]);
  async function choose(id: string) { const summary = workspace?.data.find((row) => row.id === id); if (!summary) return; setFeedback(emptyFeedback()); try { setSelected(await getSafetyRecord(summary.kind, id)); setEditing(false); } catch (error) { applyFailure(setFeedback, error, 'Unable to load safety detail.'); } }
  function startHold() { setSelected(null); setForm(blankHold()); setEditing(true); setFeedback(emptyFeedback()); }
  async function save(event: FormEvent) {
    event.preventDefault(); const order = workspace?.lookups.production_orders.find((row) => row.id === form.production_order_id); const fields: Record<string, string> = {}; if (!form.hold_number.trim()) fields.hold_number = 'Hold number is required.'; if (!order) fields.production_order_id = 'Choose a production batch.'; if (!form.reason.trim()) fields.reason = 'Describe the food-safety reason.'; if (Object.keys(fields).length || !order) { setFeedback({ error: 'Correct the highlighted hold fields.', success: null, fields }); return; }
    setBusy(true); try { key.current ??= crypto.randomUUID(); const result = await createFoodSafetyHold(order, { hold_number: form.hold_number.trim().toUpperCase(), production_order_id: order.id, hazard_type: form.hazard_type, reason: form.reason.trim() }, key.current); key.current = null; await refresh(); const row = await getSafetyRecord('HOLD', result.id); setSelected(row); setEditing(false); setFeedback({ error: null, success: 'Food-safety hold placed and batch quality blocked.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to place the food-safety hold.'); } finally { setBusy(false); }
  }
  async function recordAction(action: 'RELEASE' | 'RESOLVE') {
    if (!selected) return; const corrective = window.prompt('Corrective action'); if (!corrective?.trim()) return; const root = window.prompt('Root cause'); if (!root?.trim()) return; const disposition = window.prompt(`Disposition: ${workspace?.lookups.deviation_dispositions.join(', ')}`, workspace?.lookups.deviation_dispositions[0]); if (!disposition?.trim()) return;
    setBusy(true); try { const resolution = { disposition: disposition.trim().toUpperCase(), root_cause: root.trim(), corrective_action: corrective.trim() }; action === 'RELEASE' ? await releaseFoodSafetyHold(selected, resolution, crypto.randomUUID()) : await resolveQualityDeviation(selected, resolution, crypto.randomUUID()); await refresh(); setSelected(await getSafetyRecord(selected.kind, selected.id)); setFeedback({ error: null, success: action === 'RELEASE' ? 'Food-safety hold released.' : 'Quality deviation resolved.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to update the safety record.'); } finally { setBusy(false); }
  }
  async function releaseQuality() { const order = workspace?.lookups.production_orders.find((row) => row.id === releaseOrderId); if (!order) return; setBusy(true); try { await releaseBatchQuality(order, crypto.randomUUID()); await refresh(); setReleaseOrderId(''); setFeedback({ error: null, success: 'Batch passed the lab, deviation, and food-safety release gates.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to release batch quality.'); } finally { setBusy(false); } }
  const releaseOrders = workspace?.lookups.production_orders.filter((row) => row.status === 'COMPLETED' && row.quality_status !== 'RELEASED') ?? [];
  return <ManufacturingWorkspace code="QC-SAFE" title="Safety / Deviations" description="Control food-safety holds, resolve lab deviations, and release compliant production batches." notice="Quality release is blocked unless the latest lab sample passed and all holds and deviations are closed." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} onNew={workspace?.allowed_actions.includes('HOLD') ? startHold : undefined} headings={['Type / number', 'Order / batch', 'Category', 'Occurred', 'Status']} rows={workspace?.data.map((row) => [<><b>{row.kind}</b><small>{row.number}</small></>, <><b>{row.production_order.number}</b><small>{row.production_order.batch_number}</small></>, row.category, dateTime(row.occurred_at), <StatusBadge status={row.status} />]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {editing ? <form className="requisition-form" onSubmit={save}><fieldset disabled={busy}><div className="requisition-field-grid"><label>Hold number<input value={form.hold_number} onChange={(e) => setForm({ ...form, hold_number: e.target.value })} /><Field text={feedback.fields.hold_number} /></label><label>Hazard type<select aria-label="Hazard type" value={form.hazard_type} onChange={(e) => setForm({ ...form, hazard_type: e.target.value })}>{workspace?.lookups.hazard_types.map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide">Production batch<select aria-label="Production batch for hold" value={form.production_order_id} onChange={(e) => setForm({ ...form, production_order_id: e.target.value })}><option value="">Select batch</option>{workspace?.lookups.production_orders.map((order) => <option key={order.id} value={order.id}>{order.number} / {order.batch_number} · {order.status} / {order.quality_status}</option>)}</select><Field text={feedback.fields.production_order_id} /></label><label className="wide">Reason<textarea aria-label="Hold reason" rows={4} value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /><Field text={feedback.fields.reason} /></label></div><FormActions busy={busy} onClose={() => setEditing(false)} submit="Place food-safety hold" /></fieldset></form>
      : selected ? <Detail><DetailHead status={selected.status} version={selected.record_version} label={selected.kind} /><dl className="control-definition"><Datum text="Number" value={selected.number} /><Datum text="Production batch" value={`${selected.production_order.number} / ${selected.production_order.batch_number}`} /><Datum text="Category" value={selected.category} /><Datum text="Occurred" value={dateTime(selected.occurred_at)} /><Datum wide text="Description" value={selected.description} /><Datum text="Disposition" value={selected.disposition ?? '—'} /><Datum text="Resolved" value={dateTime(selected.resolved_at)} /><Datum wide text="Root cause" value={selected.root_cause ?? '—'} /><Datum wide text="Corrective action" value={selected.corrective_action ?? '—'} /></dl><div className="form-actions">{selected.allowed_actions.includes('RELEASE') ? <button className="primary" disabled={busy} onClick={() => void recordAction('RELEASE')}>Release hold</button> : null}{selected.allowed_actions.includes('RESOLVE') ? <button className="primary" disabled={busy} onClick={() => void recordAction('RESOLVE')}>Resolve deviation</button> : null}</div></Detail>
      : <Empty text="Choose a deviation or hold, or place a new food-safety hold." />}
    {releaseOrders.length ? <div className="quality-release-panel"><h4>Batch quality release</h4><p>Run all release gates for a completed batch.</p><label>Completed batch<select aria-label="Batch quality release" value={releaseOrderId} onChange={(e) => setReleaseOrderId(e.target.value)}><option value="">Select batch</option>{releaseOrders.map((order) => <option key={order.id} value={order.id}>{order.number} / {order.batch_number} · {order.quality_status}</option>)}</select></label><div className="form-actions"><button className="primary" disabled={!releaseOrderId || busy} onClick={() => void releaseQuality()}>Release batch quality</button></div></div> : null}
  </ManufacturingWorkspace>;
}

function blankSample() { return { sample_number: '', production_order_id: '', specification_id: '', sampled_at: localDateTime(), notes: '' }; }
function blankHold() { return { hold_number: '', production_order_id: '', hazard_type: 'ALLERGEN', reason: '' }; }
function localDateTime() { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function requirement(result: NonNullable<LabSample['results']>[number]) { if (result.value_type === 'NUMERIC') return `Range ${result.minimum_value ?? '—'} to ${result.maximum_value ?? '—'} ${result.uom_code ?? ''}; target ${result.target_value ?? '—'}`; if (result.value_type === 'BOOLEAN') return `Required answer: ${result.text_requirement ?? 'true'}`; return result.text_requirement ?? 'Enter the observed value.'; }
