import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import {
  calculateBatchCost, closeRecallCase, createRecallCase, getBatchCost, getLotTrace, getRecallCase,
  listBatchCosts, listRecallCases, type BatchCost, type BatchCostWorkspace as CostData,
  type RecallCase, type RecallWorkspace as RecallData, type TraceGraph,
} from '../api/manufacturingExecution';
import { StatusBadge } from './StatusBadge';
import {
  applyFailure, dateTime, Datum, decimal, Detail, DetailHead, emptyFeedback, Empty, Field,
  FormActions, LineTable, ManufacturingWorkspace, numeric, useManufacturingContextKey,
} from './ManufacturingWorkspaceShell';

export function TraceRecallWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<RecallData | null>(null); const [selected, setSelected] = useState<RecallCase | null>(null); const [editing, setEditing] = useState(false); const [form, setForm] = useState(blankRecall()); const [traceLotId, setTraceLotId] = useState(''); const [trace, setTrace] = useState<TraceGraph | null>(null);
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(emptyFeedback()); const key = useRef<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); try { setWorkspace(await listRecallCases({ q: search || undefined, status: status || undefined, sort, page })); } catch (error) { applyFailure(setFeedback, error, 'Unable to load recall cases.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { setSelected(null); setEditing(false); setTrace(null); setTraceLotId(''); setSearch(''); setStatus(''); setPage(1); setFeedback(emptyFeedback()); }, [contextKey]); useEffect(() => { key.current = null; }, [form]);
  async function choose(id: string) { setFeedback(emptyFeedback()); try { const row = await getRecallCase(id); setSelected(row); setTrace(row.trace ?? null); setTraceLotId(row.source_lot.id); setEditing(false); } catch (error) { applyFailure(setFeedback, error, 'Unable to load recall detail.'); } }
  function startNew() { setSelected(null); setTrace(null); setForm(blankRecall()); setEditing(true); setFeedback(emptyFeedback()); }
  async function save(event: FormEvent) { event.preventDefault(); const fields: Record<string, string> = {}; if (!form.recall_number.trim()) fields.recall_number = 'Recall number is required.'; if (!form.source_lot_id) fields.source_lot_id = 'Choose a source lot.'; if (!form.reason.trim()) fields.reason = 'Describe the recall reason.'; if (Object.keys(fields).length) { setFeedback({ error: 'Correct the highlighted recall fields.', success: null, fields }); return; } setBusy(true); try { key.current ??= crypto.randomUUID(); const result = await createRecallCase({ recall_number: form.recall_number.trim().toUpperCase(), source_lot_id: form.source_lot_id, classification: form.classification, reason: form.reason.trim() }, key.current); key.current = null; await refresh(); await choose(result.id); setFeedback({ error: null, success: 'Recall opened; all connected lots were snapshotted and on-hand stock blocked.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to open the recall case.'); } finally { setBusy(false); } }
  async function close() { if (!selected) return; const action = window.prompt('Closure action and evidence'); if (!action?.trim()) return; setBusy(true); try { await closeRecallCase(selected, action.trim(), crypto.randomUUID()); await refresh(); await choose(selected.id); setFeedback({ error: null, success: 'Recall case closed with its containment action recorded.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to close the recall case.'); } finally { setBusy(false); } }
  async function inspectTrace() { if (!traceLotId) return; setBusy(true); try { setTrace(await getLotTrace(traceLotId)); setSelected(null); setEditing(false); setFeedback({ error: null, success: 'Lot genealogy and customer exposure refreshed.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to trace the selected lot.'); } finally { setBusy(false); } }
  return <ManufacturingWorkspace code="TRACE-CASE" title="Trace / Recall" description="Traverse lot genealogy, identify shipment exposure, contain affected stock, and manage recall closure." notice="Recall initiation snapshots the full connected lot graph and atomically moves all on-hand affected stock to blocked positions." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} onNew={workspace?.allowed_actions.includes('CREATE') ? startNew : undefined} headings={['Recall', 'Source lot', 'Class', 'Affected lots', 'Initiated', 'Status']} rows={workspace?.data.map((row) => [row.recall_number, row.source_lot.code, row.classification, String(row.affected_lot_count), dateTime(row.initiated_at), <StatusBadge status={row.status} />]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {editing ? <form className="requisition-form" onSubmit={save}><fieldset disabled={busy}><div className="requisition-field-grid"><label>Recall number<input value={form.recall_number} onChange={(e) => setForm({ ...form, recall_number: e.target.value })} /><Field text={feedback.fields.recall_number} /></label><label>Classification<select aria-label="Recall classification" value={form.classification} onChange={(e) => setForm({ ...form, classification: e.target.value })}>{workspace?.lookups.classifications.map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide">Source lot<select aria-label="Recall source lot" value={form.source_lot_id} onChange={(e) => setForm({ ...form, source_lot_id: e.target.value })}><option value="">Select lot</option>{workspace?.lookups.lots.map((lot) => <option key={lot.id} value={lot.id}>{lot.code} · {lot.item_code} · {lot.status}</option>)}</select><Field text={feedback.fields.source_lot_id} /></label><label className="wide">Reason<textarea aria-label="Recall reason" rows={4} value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /><Field text={feedback.fields.reason} /></label></div><FormActions busy={busy} onClose={() => setEditing(false)} submit="Open recall and block stock" /></fieldset></form>
      : selected ? <Detail><DetailHead status={selected.status} version={selected.record_version} /><dl className="control-definition"><Datum text="Recall" value={selected.recall_number} /><Datum text="Source lot" value={selected.source_lot.code} /><Datum text="Classification" value={selected.classification} /><Datum text="Affected lots" value={selected.affected_lot_count} /><Datum text="Initiated" value={dateTime(selected.initiated_at)} /><Datum text="Closed" value={dateTime(selected.closed_at)} /><Datum wide text="Reason" value={selected.reason} /><Datum wide text="Closure action" value={selected.closure_action ?? '—'} /></dl><h4>Containment snapshot</h4><LineTable heads={['Depth', 'Lot', 'Material', 'Relationship', 'On hand', 'Action']} rows={selected.lots?.map((lot) => [String(lot.depth), lot.code, <><b>{lot.item_code}</b><small>{lot.item_name}</small></>, lot.relationship, decimal(lot.on_hand_quantity), <StatusBadge status={lot.action_status} />]) ?? []} /><div className="form-actions">{selected.allowed_actions.includes('CLOSE') ? <button className="primary" disabled={busy} onClick={() => void close()}>Close recall case</button> : null}</div></Detail>
      : <Empty text="Choose a recall case, open one, or inspect a lot without starting a recall." />}
    {!editing ? <div className="trace-explorer"><h4>Lot genealogy explorer</h4><div className="inline-fields"><label>Traceable lot<select aria-label="Traceable lot" value={traceLotId} onChange={(e) => setTraceLotId(e.target.value)}><option value="">Select lot</option>{workspace?.lookups.lots.map((lot) => <option key={lot.id} value={lot.id}>{lot.code} · {lot.item_code}</option>)}</select></label><button className="secondary" disabled={!traceLotId || busy} onClick={() => void inspectTrace()}>Trace lot</button></div>{trace ? <TraceView trace={trace} /> : null}</div> : null}
  </ManufacturingWorkspace>;
}

export function BatchCostWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<CostData | null>(null); const [selected, setSelected] = useState<BatchCost | null>(null); const [editing, setEditing] = useState(false); const [form, setForm] = useState(blankCost());
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(emptyFeedback()); const key = useRef<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); try { setWorkspace(await listBatchCosts({ q: search || undefined, status: status || undefined, sort, page })); } catch (error) { applyFailure(setFeedback, error, 'Unable to load batch costs.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { setSelected(null); setEditing(false); setSearch(''); setStatus(''); setPage(1); setFeedback(emptyFeedback()); }, [contextKey]); useEffect(() => { key.current = null; }, [form]);
  async function choose(id: string) { setFeedback(emptyFeedback()); try { setSelected(await getBatchCost(id)); setEditing(false); } catch (error) { applyFailure(setFeedback, error, 'Unable to load batch-cost detail.'); } }
  function startNew() { setSelected(null); setForm(blankCost()); setEditing(true); setFeedback(emptyFeedback()); }
  function chooseOrder(id: string) { const order = workspace?.lookups.production_orders.find((row) => row.id === id); setForm((row) => ({ ...row, production_order_id: id, material_costs: order?.materials.map((material) => ({ production_order_material_id: material.id, item_code: material.item_code, item_name: material.item_name, issued_quantity: material.issued_quantity, uom_code: material.uom_code, unit_cost: '' })) ?? [] })); }
  async function save(event: FormEvent) { event.preventDefault(); const fields: Record<string, string> = {}; if (!form.cost_number.trim()) fields.cost_number = 'Cost number is required.'; if (!form.production_order_id) fields.production_order_id = 'Choose a completed production batch.'; form.material_costs.forEach((line, index) => { if (numeric(line.unit_cost) < 0 || line.unit_cost === '') fields[`material_costs.${index}.unit_cost`] = 'Enter a non-negative unit cost.'; }); if (Object.keys(fields).length) { setFeedback({ error: 'Correct the highlighted costing fields.', success: null, fields }); return; } setBusy(true); try { key.current ??= crypto.randomUUID(); const result = await calculateBatchCost({ cost_number: form.cost_number.trim().toUpperCase(), production_order_id: form.production_order_id, labour_rate_per_minute: form.labour_rate_per_minute, overhead_rate_per_minute: form.overhead_rate_per_minute, material_costs: form.material_costs.map((line) => ({ production_order_material_id: line.production_order_material_id, unit_cost: line.unit_cost })) }, key.current); key.current = null; await refresh(); await choose(result.id); setFeedback({ error: null, success: 'Batch cost finalized from immutable material, stage, and yield snapshots.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to calculate the batch cost.'); } finally { setBusy(false); } }
  function patchUnitCost(index: number, value: string) { setForm((row) => ({ ...row, material_costs: row.material_costs.map((line, position) => position === index ? { ...line, unit_cost: value } : line) })); }
  return <ManufacturingWorkspace code="COST-BATCH" title="Batch Cost" description="Finalize material usage, conversion time, yield, unit cost, and plan-to-actual variance by batch." notice="Each calculation is an immutable versioned snapshot, so later rate changes never rewrite prior batch economics." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} onNew={workspace?.allowed_actions.includes('CALCULATE') ? startNew : undefined} headings={['Cost snapshot', 'Production batch', 'Actual cost', 'Variance', 'Yield', 'Unit cost']} rows={workspace?.data.map((row) => [<><b>{row.cost_number}</b><small>snapshot {row.snapshot_version}</small></>, `${row.production_order.number} / ${row.production_order.batch_number}`, `${row.currency} ${decimal(row.actual_total_cost)}`, `${row.currency} ${decimal(row.total_variance)} (${decimal(row.variance_percent)}%)`, `${decimal(row.yield_percent)}%`, `${row.currency} ${decimal(row.cost_per_good_unit)}`]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {editing ? <form className="requisition-form" onSubmit={save}><fieldset disabled={busy}><div className="requisition-field-grid"><label>Cost number<input value={form.cost_number} onChange={(e) => setForm({ ...form, cost_number: e.target.value })} /><Field text={feedback.fields.cost_number} /></label><label>Completed production batch<select aria-label="Cost production batch" value={form.production_order_id} onChange={(e) => chooseOrder(e.target.value)}><option value="">Select batch</option>{workspace?.lookups.production_orders.map((order) => <option key={order.id} value={order.id}>{order.number} / {order.batch_number}</option>)}</select><Field text={feedback.fields.production_order_id} /></label><label>Labour rate / minute<input aria-label="Labour rate per minute" type="number" min="0" step="0.000001" value={form.labour_rate_per_minute} onChange={(e) => setForm({ ...form, labour_rate_per_minute: e.target.value })} /></label><label>Overhead rate / minute<input aria-label="Overhead rate per minute" type="number" min="0" step="0.000001" value={form.overhead_rate_per_minute} onChange={(e) => setForm({ ...form, overhead_rate_per_minute: e.target.value })} /></label></div><h4>Material unit costs</h4>{form.material_costs.map((line, index) => <div className="requisition-line-card" key={line.production_order_material_id}><b>{line.item_code} · {line.item_name}</b><small>Issued {decimal(line.issued_quantity)} {line.uom_code}</small><label>Unit cost<input aria-label={`${line.item_code} unit cost`} type="number" min="0" step="0.000001" value={line.unit_cost} onChange={(e) => patchUnitCost(index, e.target.value)} /><Field text={feedback.fields[`material_costs.${index}.unit_cost`]} /></label></div>)}<FormActions busy={busy} onClose={() => setEditing(false)} submit="Finalize cost snapshot" /></fieldset></form>
      : selected ? <Detail><DetailHead status={selected.status} label={`snapshot ${selected.snapshot_version}`} /><dl className="control-definition"><Datum text="Cost snapshot" value={selected.cost_number} /><Datum text="Production batch" value={`${selected.production_order.number} / ${selected.production_order.batch_number}`} /><Datum text="Calculated" value={dateTime(selected.calculated_at)} /><Datum text="Yield" value={`${decimal(selected.good_quantity)} good · ${decimal(selected.yield_percent)}%`} /><Datum text="Planned material" value={`${selected.currency} ${decimal(selected.planned_material_cost)}`} /><Datum text="Actual material" value={`${selected.currency} ${decimal(selected.actual_material_cost)}`} /><Datum text="Planned conversion" value={`${selected.currency} ${decimal(selected.planned_conversion_cost)}`} /><Datum text="Actual conversion" value={`${selected.currency} ${decimal(selected.actual_conversion_cost)}`} /><Datum text="Planned total" value={`${selected.currency} ${decimal(selected.planned_total_cost)}`} /><Datum text="Actual total" value={`${selected.currency} ${decimal(selected.actual_total_cost)}`} /><Datum text="Total variance" value={`${selected.currency} ${decimal(selected.total_variance)} · ${decimal(selected.variance_percent)}%`} /><Datum text="Cost / good unit" value={`${selected.currency} ${decimal(selected.cost_per_good_unit)}`} /></dl><h4>Material usage variance</h4><LineTable heads={['Material', 'Plan / actual', 'Unit cost', 'Plan / actual cost', 'Usage variance']} rows={selected.materials?.map((line) => [<><b>{line.item_code}</b><small>{line.item_name}</small></>, `${decimal(line.planned_quantity)} / ${decimal(line.actual_quantity)} ${line.uom_code}`, decimal(line.unit_cost), `${decimal(line.planned_cost)} / ${decimal(line.actual_cost)}`, decimal(line.usage_variance)]) ?? []} /><h4>Stage time variance</h4><LineTable heads={['Work centre', 'Plan / actual min', 'Plan / actual cost', 'Time variance']} rows={selected.stages?.map((line) => [line.work_center_code, `${decimal(line.planned_minutes)} / ${decimal(line.actual_minutes)}`, `${decimal(line.planned_cost)} / ${decimal(line.actual_cost)}`, decimal(line.time_variance)]) ?? []} /></Detail> : <Empty text="Choose a batch-cost snapshot or calculate one for a completed batch." />}
  </ManufacturingWorkspace>;
}

function TraceView({ trace }: { trace: TraceGraph }) { return <div className="trace-view"><div className="manufacturing-balance"><span>Root lot<b>{trace.lot.code}</b></span><span>Connected lots<b>{trace.nodes.length}</b></span><span>Genealogy links<b>{trace.edges.length}</b></span><span>Shipments<b>{trace.shipments.length}</b></span></div><LineTable heads={['Depth', 'Lot', 'Item', 'Status']} rows={trace.nodes.map((node) => [String(node.depth ?? 0), node.code, `${node.item?.code ?? node.item_code ?? 'Unknown item'} · ${node.item?.name ?? node.item_name ?? 'Name unavailable'}`, <StatusBadge status={node.status} />])} />{trace.shipments.length ? <><h4>Customer exposure</h4><LineTable heads={['Shipment', 'Customer', 'Lot', 'Shipped / returned']} rows={trace.shipments.map((row) => [row.number, row.customer ? `${row.customer.code} · ${row.customer.name}` : 'Unassigned', trace.nodes.find((node) => node.id === row.lot_id)?.code ?? row.lot_id, `${decimal(row.shipped_quantity)} / ${decimal(row.returned_quantity)} ${row.uom_code}`])} /></> : <p className="trace-clear">No shipment exposure for this connected lot graph.</p>}</div>; }
function blankRecall() { return { recall_number: '', source_lot_id: '', classification: 'CLASS_II', reason: '' }; }
function blankCost() { return { cost_number: '', production_order_id: '', labour_rate_per_minute: '0', overhead_rate_per_minute: '0', material_costs: [] as { production_order_material_id: string; item_code: string; item_name: string; issued_quantity: string; uom_code: string; unit_cost: string }[] }; }
